// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace prj030.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203104314_MapRootOwnedTipes")]
    partial class MapRootOwnedTipes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Root", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("Root", b =>
                {
                    b.OwnsOne("Meta", "meta", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("page")
                                .HasColumnType("int")
                                .HasColumnName("Meta_Page");

                            b1.Property<int>("size")
                                .HasColumnType("int")
                                .HasColumnName("Meta_Size");

                            b1.Property<int>("totalData")
                                .HasColumnType("int");

                            b1.Property<int>("totalPage")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.ToTable("Anime");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsMany("Datum", "data", b1 =>
                        {
                            b1.Property<string>("_id")
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<int>("RootId")
                                .HasColumnType("int");

                            b1.Property<int>("__v")
                                .HasColumnType("int");

                            b1.PrimitiveCollection<string>("alternativeTitles")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("episodes")
                                .HasColumnType("int");

                            b1.PrimitiveCollection<string>("genres")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<bool>("hasEpisode")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("hasRanking")
                                .HasColumnType("tinyint(1)");

                            b1.Property<string>("id")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)");

                            b1.Property<string>("image")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("varchar(300)");

                            b1.Property<string>("link")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("varchar(300)");

                            b1.Property<int>("ranking")
                                .HasColumnType("int");

                            b1.Property<double>("score")
                                .HasColumnType("double");

                            b1.Property<string>("status")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("synopsis")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("thumb")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("title")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("varchar(300)");

                            b1.Property<string>("type")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<DateTime>("updatedAt")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("workerId")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("_id");

                            b1.HasIndex("RootId");

                            b1.ToTable("Datum", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RootId");
                        });

                    b.Navigation("data");

                    b.Navigation("meta")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
