// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace prj030.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203094030_MakeSynopsisLongtext")]
    partial class MakeSynopsisLongtext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Datum", b =>
                {
                    b.Property<string>("_id")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("RootId")
                        .HasColumnType("int");

                    b.Property<int>("__v")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("alternativeTitles")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("episodes")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("genres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("hasEpisode")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("hasRanking")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("id")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("link")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("ranking")
                        .HasColumnType("int");

                    b.Property<double>("score")
                        .HasColumnType("double");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("synopsis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("thumb")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("workerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("_id");

                    b.HasIndex("RootId");

                    b.ToTable("Datum");
                });

            modelBuilder.Entity("Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("page")
                        .HasColumnType("int");

                    b.Property<int>("size")
                        .HasColumnType("int");

                    b.Property<int>("totalData")
                        .HasColumnType("int");

                    b.Property<int>("totalPage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Meta");
                });

            modelBuilder.Entity("Root", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("metaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("metaId");

                    b.ToTable("Anime");
                });

            modelBuilder.Entity("Datum", b =>
                {
                    b.HasOne("Root", null)
                        .WithMany("data")
                        .HasForeignKey("RootId");
                });

            modelBuilder.Entity("Root", b =>
                {
                    b.HasOne("Meta", "meta")
                        .WithMany()
                        .HasForeignKey("metaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("meta");
                });

            modelBuilder.Entity("Root", b =>
                {
                    b.Navigation("data");
                });
#pragma warning restore 612, 618
        }
    }
}
